version: '3.8'

services:
  server:
    build: ./server
    image: better-server
    ports:
      - "5000:5000"
    networks:
      - app-network

  client:
    build: ./client
    image: better-client
    ports:
      - "3000:80"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
      - client
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
