version: '3'
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    networks:
      - app-network

  client:
    build: ./client
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
