spring.application.name=server

#mc server address
mcstatus.api.base-url=https://api.mcstatus.io/v2
mcstatus.server.address=thursday-threefold.gl.joinmc.link

#sqlite database
spring.datasource.url=jdbc:postgresql://localhost:5432/better_server
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

#frontend
client.vite.url=http://localhost:3000