spring.application.name=server

#mc server address
mcstatus.api.base-url=https://api.mcstatus.io/v2
mcstatus.server.address=

#sqlite database
spring.datasource.url=jdbc:sqlite:src/main/resources/db/betterserver.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.data-source-properties.journal_mode=WAL
spring.datasource.hikari.data-source-properties.busy_timeout=30000

#frontend
client.vite.url=

#authentication
jwt.cookie.secure=
jwt.secret=
jwt.expiration-ms=604800000

#limit max size of uploaded files
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

#for fetching mc player information
mcstats.world-stats-directory=
mcstats.import-interval-ms=3600000

#caching
spring.cache.cache-names=playersByUuid,playersByUsername
spring.cache.caffeine.spec=maximumSize=10000,expireAfterWrite=5h