spring.application.name=server

#mc server address
mcstatus.api.base-url=https://api.mcstatus.io/v2
mcstatus.server.address=thursday-threefold.gl.joinmc.link

#MySQL database
spring.datasource.url=jdbc:mysql://localhost:3306/betterserver?createDatabaseIfNotExist=true
spring.jpa.hibernate.ddl-auto=update