name: Publish Client and Server Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.sha }}
      DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Build client image
        run: |
          docker-compose build client
          IMAGE_ID=$(docker inspect --format="{{.Id}}" $(docker-compose images -q client))
          docker tag $IMAGE_ID $DOCKER_USER/client:latest
          docker tag $IMAGE_ID $DOCKER_USER/client:$IMAGE_TAG

      - name: Build server image
        run: |
          docker-compose build server
          IMAGE_ID=$(docker inspect --format="{{.Id}}" $(docker-compose images -q server))
          docker tag $IMAGE_ID $DOCKER_USER/server:latest
          docker tag $IMAGE_ID $DOCKER_USER/server:$IMAGE_TAG

      - name: Push client image
        run: |
          docker push $DOCKER_USER/client:latest
          docker push $DOCKER_USER/client:$IMAGE_TAG

      - name: Push server image
        run: |
          docker push $DOCKER_USER/server:latest
          docker push $DOCKER_USER/server:$IMAGE_TAG
